// Generated by WebFx

module webfx.demo.responsivedesign.application {

    // Direct dependencies modules
    requires javafx.controls;
    requires javafx.graphics;

    // Exported packages
    exports dev.webfx.demo.responsivedesign;

    // Provided services
    provides javafx.application.Application with dev.webfx.demo.responsivedesign.ResponsiveDesignApplication;

}